package:
  name: ros-humble-ament-cmake-nose
  version: 1.3.3
source:
  git_url: https://github.com/ros2-gbp/ament_cmake-release.git
  git_rev: release/humble/ament_cmake_nose/1.3.3-1
  folder: ros-humble-ament-cmake-nose/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 3
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - setuptools
    - sel(unix): make
    - sel(unix): coreutils
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(build_platform != target_platform): numpy
  host:
    - nose
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - ros-humble-ament-cmake-core
    - ros-humble-ament-cmake-test
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros2-distro-mutex 0.3 humble
  run:
    - nose
    - python
    - ros-humble-ament-cmake-core
    - ros-humble-ament-cmake-test
    - ros-humble-ros-workspace
    - ros2-distro-mutex 0.3 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
