package:
  name: ros-humble-turtlebot3-msgs
  version: 2.2.3
source:
  git_url: https://github.com/ros2-gbp/turtlebot3_msgs-release.git
  git_rev: release/humble/turtlebot3_msgs/2.2.3-1
  folder: ros-humble-turtlebot3-msgs/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 3
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - setuptools
    - sel(unix): make
    - sel(unix): coreutils
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(build_platform != target_platform): numpy
  host:
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - ros-humble-action-msgs
    - ros-humble-ament-cmake
    - ros-humble-ament-lint-common
    - ros-humble-builtin-interfaces
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-rosidl-default-generators
    - ros-humble-rosidl-default-runtime
    - ros-humble-std-msgs
    - ros2-distro-mutex 0.3 humble
  run:
    - python
    - ros-humble-action-msgs
    - ros-humble-builtin-interfaces
    - ros-humble-ros-workspace
    - ros-humble-rosidl-default-runtime
    - ros-humble-std-msgs
    - ros2-distro-mutex 0.3 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
