package:
  name: ros-humble-foxglove-bridge
  version: 0.5.1
source:
  git_url: https://github.com/ros2-gbp/foxglove_bridge-release.git
  git_rev: release/humble/foxglove_bridge/0.5.1-1
  folder: ros-humble-foxglove-bridge/src/work
  patches:
    - patch/ros-humble-foxglove-bridge.patch

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 3
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - setuptools
    - sel(unix): make
    - sel(unix): coreutils
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(build_platform != target_platform): numpy
  host:
    - asio
    - nlohmann_json
    - numpy
    - openssl
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - ros-humble-ament-cmake
    - ros-humble-ament-cmake-gtest
    - ros-humble-ament-index-cpp
    - ros-humble-ament-lint-auto
    - ros-humble-rclcpp
    - ros-humble-rclcpp-components
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-rosgraph-msgs
    - ros-humble-std-msgs
    - ros-humble-std-srvs
    - ros2-distro-mutex 0.3 humble
    - websocketpp
    - zlib
  run:
    - openssl
    - python
    - ros-humble-ament-index-cpp
    - ros-humble-rclcpp
    - ros-humble-rclcpp-components
    - ros-humble-ros-workspace
    - ros-humble-rosgraph-msgs
    - ros2-distro-mutex 0.3 humble
    - zlib
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
